do_over - for flaky (i.e. ALL) services <span style="float:right;">[&#x25C0;](24.md) [&#x25B2;](../README.md) [&#x25BA;](26.md)</span>
=========

## the internet is unreliable

We rely so much now on services that are out of our control and expected to fail temporarily.

For example:

* __S3 calls are expected to fail frequently__, they're documented this way, and you should try again
* Most service APIs document failures
* Maybe someone accidentally tripped over an ethernet cable somewhere, and they'll plug it in in a second
* shit happens

## Helper: [do_over.py](https://github.com/BrentNoorda/django_unusual/blob/master/lib/do_over.py)

[do_over.py](https://github.com/BrentNoorda/django_unusual/blob/master/lib/do_over.py) provides a _do_over()_ method that I've found very helpful in situation where occasional failure is expected.

## Let's fix the weather example

Remember that our call to get the weather is failing 20% of the time. __The user shouldn't have to see this__, we should just do a do-over.

There are a lot of options for _do_over()_, but we'll just look at a simple case:

[favorite_color_with_temperature_and_db.mako](https://github.com/BrentNoorda/django_unusual/blob/master/django_unusual/mako/examples/favorite_color_with_temperature_and_db.mako) was failing 20% of the time here:

    current_temperature = lib.oakland_weather.get_current_oakland_weather(fail_sometimes_on_purpose=True)

so we'll make [favorite_color_with_temperature_and_db_do_over.mako](https://github.com/BrentNoorda/django_unusual/blob/master/django_unusual/mako/examples/favorite_color_with_temperature_and_db_do_over.mako) and change that to:

    current_temperature = do_over( lambda x: lib.oakland_weather.get_current_oakland_weather(fail_sometimes_on_purpose=True) )

Try it: __[http://MY_IP_ADDRESS:8000/examples/favorite_color_with_temperature_and_db_do_over.mako](http://MY_IP_ADDRESS:8000/examples/favorite_color_with_temperature_and_db_do_over.mako)__

Even though the yahoo call is still failing 20% of the time, it would have to fail a lot of times, after fallback timeouts, before it really failed.

## WHAT ABOUT DB CALLS? SHOULD WE RECOVER?

Good question. Our calls to our database (whether directly or via the django ORM) might fail, right? Should we do_over those calls?

Yes, but it gets complicated and beyond what I want to discuss in this presentation.

## More about this topic?

See [We reserve the right to refuse this web service to anyone.](http://blog.problemssolvingproblems.com/2012/05/we-reserve-right-to-refuse-this-web.html) (*shameless plug*)

------

&nbsp;&nbsp;&nbsp;&nbsp; [&lt;&lt; prev](24.md) -- [top](../README.md) -- [next &gt;&gt;](26.md)